// Mocks generated by Mockito 5.4.6 from annotations
// in logbook_app_079/test/module4_counter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:logbook_app_079/models/logbook_model.dart' as _i4;
import 'package:logbook_app_079/services/mongo_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mongo_dart/mongo_dart.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MongoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMongoService extends _i1.Mock implements _i2.MongoService {
  MockMongoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Logbook>> getLogs() =>
      (super.noSuchMethod(
            Invocation.method(#getLogs, []),
            returnValue: _i3.Future<List<_i4.Logbook>>.value(<_i4.Logbook>[]),
          )
          as _i3.Future<List<_i4.Logbook>>);

  @override
  _i3.Future<void> insertLog(_i4.Logbook? log) =>
      (super.noSuchMethod(
            Invocation.method(#insertLog, [log]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateLog(_i4.Logbook? log) =>
      (super.noSuchMethod(
            Invocation.method(#updateLog, [log]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteLog(_i5.ObjectId? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLog, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
